version: '3.8'

services:
  mongodb:
    image: mongo:8.0.11
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db           # Bind mount to local data folder
      - ./configdb:/data/configdb  # Optional metadata storage
    networks:
      - mongo_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  mongo_net:
    driver: bridge
