version: '3.8'

services:
  mongodb:
    image: mongo:8.0.11
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/db/data
      - ./configdb:/data/configdb
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - backend_net
    restart: always

networks:
  backend_net:
    driver: bridge

volumes:
  redis_data:
